name: Deploy to Staging

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/deploy-web.yml
    with:
      branch: main
      username: ${{ vars.STAGING_JANSAHAS_WEB_USERNAME }}
      host: ${{ vars.STAGING_JANSAHAS_WEB_SERVER_IP }}
    secrets:
      ssh_key: ${{ secrets.STAGING_JANSAHAS_WEB_SSH_PRIVATE_KEY }}
      DISCORD_STAGING_BUILDS_URL: ${{ secrets.DISCORD_STAGING_BUILDS_URL}}
